version: '3'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"