version: '3'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile-ec2.dev
    env_file:
      - ./server/src/config/dev.env
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile-ec2.dev
      context: ./nginx
    ports:
      - '80:80'
  redis:
    build:
      dockerfile: Dockerfile.dev
      context: ./redis
    ports:
      - '6379:6379'
