version: '3'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - ./server/src/config/dev.env
    volumes:
      - "./server:/app"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
  client:
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - "./client:/app"
  redis:
    build:
      dockerfile: Dockerfile.dev
      context: ./redis
    ports:
      - '6379:6379'
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5000:80
    env_file:
      - ./pg-admin/dev.env
  postgres:
    image: postgres:15.4
    ports:
      - 5432:5432
    env_file:
      - ./postgres/dev.env
