import { Knex } from 'knex';
import bcryptjs from 'bcryptjs';

import { generateStrongPassword } from '../src/models/oauth.js';

const hashPassword = (password: string): Promise<string> => {
    return bcryptjs.hash(password, 10);
}

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex('users').del();

    // Inserts seed entries
    await knex('users').insert([
        // adding an administrator
        {
            email: process.env.DB_SEEDING_ADMIN_EMAIL,
            password: process.env.DB_SEEDING_ADMIN_PASSWORD,
            first_name: process.env.DB_SEEDING_ADMIN_FIRST_NAME,
            last_name: process.env.DB_SEEDING_ADMIN_LAST_NAME,
            phone_number: process.env.DB_SEEDING_ADMIN_PHONE_NUMBER || null,
            is_activated: true,
            is_admin: true,
        },
        {
            email: 'olga.kovale@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Ольга',
            last_name: 'Коваленко',
            phone_number: '+380-95-123-45-67',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'ivan.petrov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Іван',
            last_name: 'Петров',
            phone_number: '+380-97-765-43-21',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'marina.lysenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Марина',
            last_name: 'Лисенко',
            phone_number: '+380-63-987-65-43',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'andriy.shevchenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Андрій',
            last_name: 'Шевченко',
            phone_number: '+380-67-890-12-34',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'nataliya.marchenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Наталія',
            last_name: 'Марченко',
            phone_number: '+380-50-234-56-78',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergey.melnik@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Мельник',
            phone_number: '+380-68-345-67-89',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'anna.lebedeva@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Анна',
            last_name: 'Лебедєва',
            phone_number: '+380-93-456-78-90',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oleksandr.koval@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Олександр',
            last_name: 'Коваль',
            phone_number: '+380-99-567-89-01',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'mariya.popova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Марія',
            last_name: 'Попова',
            phone_number: '+380-66-890-12-34',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oleg.kozlov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Олег',
            last_name: 'Козлов',
            phone_number: '+380-95-234-56-78',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'marina.marchenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Марина',
            last_name: 'Марченко',
            phone_number: '+380-97-345-67-89',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'volodymyr.sidorov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Володимир',
            last_name: 'Сидоров',
            phone_number: '+380-63-456-78-90',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oksana.kovalenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Оксана',
            last_name: 'Коваленко',
            phone_number: '+380-67-567-89-01',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergiy.dmytruk@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Дмитрук',
            phone_number: '+380-50-678-90-12',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'nina.karpenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Ніна',
            last_name: 'Карпенко',
            phone_number: '+380-68-789-01-23',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'pavlo.romanov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Павло',
            last_name: 'Романов',
            phone_number: '+380-93-890-12-34',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'elena.shcherbak@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Олена',
            last_name: 'Щербак',
            phone_number: '+380-99-901-23-45',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'mykola.vorobiov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Микола',
            last_name: 'Воробйов',
            phone_number: '+380-66-901-23-45',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'yulia.savchenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Юлія',
            last_name: 'Савченко',
            phone_number: '+380-95-345-67-89',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'vladimir.maksymov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Володимир',
            last_name: 'Максимов',
            phone_number: '+380-97-456-78-90',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergey.ivanov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Іванов',
            phone_number: '+380-63-567-89-01',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'olga.kuznetsova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Ольга',
            last_name: 'Кузнецова',
            phone_number: '+380-67-678-90-12',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'viktor.semionov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Віктор',
            last_name: 'Семенов',
            phone_number: '+380-50-789-01-23',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'margarita.ivanova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Маргарита',
            last_name: 'Іванова',
            phone_number: '+380-68-901-23-45',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'ivan.kolosov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Іван',
            last_name: 'Колосов',
            phone_number: '+380-93-901-23-45',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oksana.ponomarenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Оксана',
            last_name: 'Пономаренко',
            phone_number: '+380-99-012-34-56',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergiy.romanenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Романенко',
            phone_number: '+380-66-012-34-56',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'nina.kudryavtseva@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Ніна',
            last_name: 'Кудрявцева',
            phone_number: '+380-95-456-78-90',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'vadim.titov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Вадим',
            last_name: 'Титов',
            phone_number: '+380-97-567-89-01',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'olena.romanova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Олена',
            last_name: 'Романова',
            phone_number: '+380-63-678-90-12',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'petro.ostapov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Петро',
            last_name: 'Остапов',
            phone_number: '+380-67-789-01-23',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'maria.smirnova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Марія',
            last_name: 'Смирнова',
            phone_number: '+380-50-901-23-45',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'andriy.pavlov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Андрій',
            last_name: 'Павлов',
            phone_number: '+380-68-012-34-56',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'daria.stepanova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Дарія',
            last_name: 'Степанова',
            phone_number: '+380-93-012-34-56',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oleg.manelenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Олег',
            last_name: 'Манеленко',
            phone_number: '+380-99-123-45-67',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'tatyana.bogdanova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Тетяна',
            last_name: 'Богданова',
            phone_number: '+380-66-123-45-67',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergey.pavlenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Павленко',
            phone_number: '+380-95-567-89-01',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'marina.popova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Марина',
            last_name: 'Попова',
            phone_number: '+380-97-678-90-12',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'andriy.kovalenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Андрій',
            last_name: 'Коваленко',
            phone_number: '+380-63-789-01-23',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oksana.melnikova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Оксана',
            last_name: 'Мельникова',
            phone_number: '+380-67-901-23-45',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergiy.pavlov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Павлов',
            phone_number: '+380-50-012-34-56',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'nina.sidorova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Ніна',
            last_name: 'Сидорова',
            phone_number: '+380-68-123-45-67',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'volodymyr.karpenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Володимир',
            last_name: 'Карпенко',
            phone_number: '+380-93-123-45-67',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'anna.dmytruk@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Анна',
            last_name: 'Дмитрук',
            phone_number: '+380-99-234-56-78',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oleksandr.kudryavtsev@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Олександр',
            last_name: 'Кудрявцев',
            phone_number: '+380-66-234-56-78',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'mariya.titova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Марія',
            last_name: 'Титова',
            phone_number: '+380-95-678-90-12',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergey.savchenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Савченко',
            phone_number: '+380-97-901-23-45',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'nina.petrov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Ніна',
            last_name: 'Петрова',
            phone_number: '+380-63-890-12-34',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'mykola.danylyuk@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Микола',
            last_name: 'Данилюк',
            phone_number: '+380-67-012-34-56',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'larysa.kovalchuk@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Лариса',
            last_name: 'Ковальчук',
            phone_number: '+380-50-123-45-67',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'andriy.kozlovsky@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Андрій',
            last_name: 'Козловський',
            phone_number: '+380-68-234-56-78',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oksana.shevchenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Оксана',
            last_name: 'Шевченко',
            phone_number: '+380-93-345-67-89',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'mykola.petrov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Микола',
            last_name: 'Петров',
            phone_number: '+380-99-456-78-90',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'olga.kravchenko@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Ольга',
            last_name: 'Кравченко',
            phone_number: '+380-66-567-89-01',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergey.ivanchuk@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Іванчук',
            phone_number: '+380-95-789-01-23',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'maria.kozlova@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Марія',
            last_name: 'Козлова',
            phone_number: '+380-97-012-34-56',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'dmytro.romanov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Дмитро',
            last_name: 'Романов',
            phone_number: '+380-63-901-23-45',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'anna.melnyk@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Анна',
            last_name: 'Мельник',
            phone_number: '+380-67-123-45-67',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'vadim.shcherbakov@gmail.com',
            password: await hashPassword(generateStrongPassword()),
            first_name: 'Вадим',
            last_name: 'Щербаков',
            phone_number: '+380-50-234-56-79',
            is_activated: true,
            is_admin: false,
        },
    ]);
}
