import { Knex } from 'knex';
import bcryptjs from 'bcryptjs';

import SignupModel from '../src/models/signup.js';

const hashPassword = (password: string): Promise<string> => {
    return bcryptjs.hash(password, 10);
};

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex('users').del();

    // Inserts seed entries
    await knex('users').insert([
        // adding an administrator
        {
            email: process.env.DB_SEEDING_ADMIN_EMAIL,
            password: process.env.DB_SEEDING_ADMIN_PASSWORD,
            first_name: process.env.DB_SEEDING_ADMIN_FIRST_NAME,
            last_name: process.env.DB_SEEDING_ADMIN_LAST_NAME,
            is_activated: true,
            is_admin: true,
        },
        {
            email: 'olga.kovale@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Ольга',
            last_name: 'Коваленко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'ivan.petrov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Іван',
            last_name: 'Петров',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'marina.lysenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Марина',
            last_name: 'Лисенко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'andriy.shevchenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Андрій',
            last_name: 'Шевченко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'nataliya.marchenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Наталія',
            last_name: 'Марченко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergey.melnik@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Мельник',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'anna.lebedeva@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Анна',
            last_name: 'Лебедєва',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oleksandr.koval@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Олександр',
            last_name: 'Коваль',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'mariya.popova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Марія',
            last_name: 'Попова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oleg.kozlov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Олег',
            last_name: 'Козлов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'marina.marchenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Марина',
            last_name: 'Марченко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'volodymyr.sidorov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Володимир',
            last_name: 'Сидоров',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oksana.kovalenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Оксана',
            last_name: 'Коваленко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergiy.dmytruk@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Дмитрук',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'nina.karpenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Ніна',
            last_name: 'Карпенко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'pavlo.romanov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Павло',
            last_name: 'Романов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'elena.shcherbak@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Олена',
            last_name: 'Щербак',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'mykola.vorobiov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Микола',
            last_name: 'Воробйов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'yulia.savchenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Юлія',
            last_name: 'Савченко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'vladimir.maksymov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Володимир',
            last_name: 'Максимов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergey.ivanov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Іванов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'olga.kuznetsova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Ольга',
            last_name: 'Кузнецова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'viktor.semionov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Віктор',
            last_name: 'Семенов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'margarita.ivanova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Маргарита',
            last_name: 'Іванова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'ivan.kolosov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Іван',
            last_name: 'Колосов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oksana.ponomarenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Оксана',
            last_name: 'Пономаренко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergiy.romanenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Романенко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'nina.kudryavtseva@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Ніна',
            last_name: 'Кудрявцева',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'vadim.titov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Вадим',
            last_name: 'Титов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'olena.romanova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Олена',
            last_name: 'Романова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'petro.ostapov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Петро',
            last_name: 'Остапов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'maria.smirnova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Марія',
            last_name: 'Смирнова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'andriy.pavlov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Андрій',
            last_name: 'Павлов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'daria.stepanova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Дарія',
            last_name: 'Степанова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oleg.manelenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Олег',
            last_name: 'Манеленко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'tatyana.bogdanova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Тетяна',
            last_name: 'Богданова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergey.pavlenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Павленко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'marina.popova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Марина',
            last_name: 'Попова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'andriy.kovalenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Андрій',
            last_name: 'Коваленко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oksana.melnikova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Оксана',
            last_name: 'Мельникова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergiy.pavlov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Павлов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'nina.sidorova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Ніна',
            last_name: 'Сидорова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'volodymyr.karpenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Володимир',
            last_name: 'Карпенко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'anna.dmytruk@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Анна',
            last_name: 'Дмитрук',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oleksandr.kudryavtsev@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Олександр',
            last_name: 'Кудрявцев',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'mariya.titova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Марія',
            last_name: 'Титова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergey.savchenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Савченко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'nina.petrov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Ніна',
            last_name: 'Петрова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'mykola.danylyuk@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Микола',
            last_name: 'Данилюк',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'larysa.kovalchuk@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Лариса',
            last_name: 'Ковальчук',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'andriy.kozlovsky@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Андрій',
            last_name: 'Козловський',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'oksana.shevchenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Оксана',
            last_name: 'Шевченко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'mykola.petrov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Микола',
            last_name: 'Петров',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'olga.kravchenko@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Ольга',
            last_name: 'Кравченко',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'sergey.ivanchuk@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Сергій',
            last_name: 'Іванчук',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'maria.kozlova@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Марія',
            last_name: 'Козлова',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'dmytro.romanov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Дмитро',
            last_name: 'Романов',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'anna.melnyk@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Анна',
            last_name: 'Мельник',
            is_activated: true,
            is_admin: false,
        },
        {
            email: 'vadim.shcherbakov@gmail.com',
            password: await hashPassword(SignupModel.generateStrongPassword()),
            first_name: 'Вадим',
            last_name: 'Щербаков',
            is_activated: true,
            is_admin: false,
        },
    ]);
}
