AWSTemplateFormatVersion: '2010-09-09'
Resources:
    AcmCertificate:
        Type: AWS::CertificateManager::Certificate
        Properties:
            DomainName: onlinestore-potapchuk.click
            CertificateTransparencyLoggingPreference: ENABLED
            ValidationMethod: DNS
    ReactApplicationS3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            # BucketName: onlinestore-potapchuk.click # must match the website name in order for it to be used with Route53
            BucketName: onlinestore-potapchuk-bucket-4562895
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false
            WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: index.html
    ReactApplicationS3BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref ReactApplicationS3Bucket
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal: '*'
                      Action: 's3:GetObject'
                      Resource: !Join ['', [!GetAtt ReactApplicationS3Bucket.Arn, '/*'] ]
    ReactApplicationCloudFrontDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Aliases:
                    - onlinestore-potapchuk.click
                Enabled: true
                Origins:
                    - DomainName: !Select [ "1", !Split [ "://", !GetAtt ReactApplicationS3Bucket.WebsiteURL ] ]
                      Id: S3Origin
                      CustomOriginConfig:
                        HTTPPort: 80
                        OriginProtocolPolicy: http-only
                DefaultCacheBehavior:
                    AllowedMethods:
                        - GET
                        - HEAD
                    CachedMethods:
                        - GET
                        - HEAD
                    TargetOriginId: S3Origin
                    ForwardedValues:
                        QueryString: false
                        Cookies:
                            Forward: none
                    ViewerProtocolPolicy: redirect-to-https
                    Compress: true
                DefaultRootObject: index.html
                ViewerCertificate:
                    AcmCertificateArn: !Ref AcmCertificate
                    MinimumProtocolVersion: TLSv1.2_2021
                    SslSupportMethod: sni-only
                PriceClass: PriceClass_100
                Comment: CloudFront distribution that's associated with the S3 bucket that hosts the React application
    ReactApplicationS3BucketRoute53Record:
        Type: AWS::Route53::RecordSet
        Properties:
            HostedZoneId: Z0929204D3TCT5NDFPB
            Name: onlinestore-potapchuk.click
            Type: A
            AliasTarget:
                DNSName: !GetAtt ReactApplicationCloudFrontDistribution.DomainName
                HostedZoneId: Z2FDTNDATAQYW2

Outputs:
    S3DomainName:
        Description: Domain Name of the S3 bucket
        Value: !GetAtt ReactApplicationS3Bucket.DomainName
    S3RegionalDomainName:
        Description: Regional Domain Name of the S3 bucket
        Value: !GetAtt ReactApplicationS3Bucket.RegionalDomainName
    S3WebsiteURL:
        Description: Website URL of the S3 bucket
        Value: !Select [ "1", !Split [ "://", !GetAtt ReactApplicationS3Bucket.WebsiteURL ] ]
