name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Go to server/src folder
        run: cd server/src
      - name: create "config" folder if it doesn't exist
        run: mkdir -p config
      - name: go to the config folder
        run: cd config
      - name: Create .env file
        run: |
          echo "${{ secrets.MAIN_ENV_FILE }}" > .env
      - name: Create postgres.env file
        run: |
          echo "${{ secrets.POSTGRES_ENV_FILE }}" > postgres.env
      - name: Go to the root folder
        run: cd ../../..
      - name: Start up the project
        run: docker-compose up
      - name: Run tests
        run: docker exec -it onlinestore-api-1 npm run test:ci
